In [94]:
import tensorflow as tf
import numpy as np
import sklearn

In [95]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [96]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.05755076, -0.6135505 , -0.28038967, -0.0276469 , -0.44235867,
         0.24564645,  0.4486359 ,  0.7143568 , -0.31883582, -0.02743676]],
      dtype=float32)

In [97]:
tf.nn.softmax(predictions).numpy()
loss_fn(y_train[:1], predictions).numpy()

2.100349

In [98]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [99]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [104]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0844 - accuracy: 0.9744
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0738 - accuracy: 0.9769
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0645 - accuracy: 0.9795
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0576 - accuracy: 0.9808
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0514 - accuracy: 0.9833


In [105]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0699 - accuracy: 0.9800


[0.06987950950860977, 0.9800000190734863]

In [106]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [107]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.6756932e-09, 9.4583035e-09, 2.8281113e-07, 1.2649973e-04,
        9.4014789e-14, 1.6894374e-08, 1.1748263e-15, 9.9987304e-01,
        5.9432931e-08, 1.7485377e-07],
       [9.1702657e-10, 3.5839079e-05, 9.9996412e-01, 1.7672081e-08,
        2.2154553e-23, 2.3691557e-08, 5.2938504e-12, 4.9211672e-16,
        3.5894381e-09, 1.1936218e-16],
       [4.3798956e-08, 9.9972075e-01, 2.3909464e-05, 6.4441326e-07,
        1.6838677e-06, 7.2483708e-08, 9.4971091e-07, 2.2277349e-04,
        2.9146904e-05, 2.6812913e-08],
       [9.9999309e-01, 7.0278332e-13, 3.5659536e-06, 2.5072524e-09,
        3.3495309e-09, 2.2077063e-07, 1.8981237e-06, 2.6933108e-07,
        3.8185757e-10, 9.1252411e-07],
       [9.4150749e-07, 1.4605134e-12, 1.1094733e-05, 2.9119263e-09,
        9.9925488e-01, 5.7946875e-07, 2.8529809e-07, 3.6004163e-05,
        4.6944507e-08, 6.9627690e-04]], dtype=float32)>

In [108]:
print(probability_model(x_test[:5]))

tf.Tensor(
[[5.6756932e-09 9.4583035e-09 2.8281113e-07 1.2649973e-04 9.4014789e-14
  1.6894374e-08 1.1748263e-15 9.9987304e-01 5.9432931e-08 1.7485377e-07]
 [9.1702657e-10 3.5839079e-05 9.9996412e-01 1.7672081e-08 2.2154553e-23
  2.3691557e-08 5.2938504e-12 4.9211672e-16 3.5894381e-09 1.1936218e-16]
 [4.3798956e-08 9.9972075e-01 2.3909464e-05 6.4441326e-07 1.6838677e-06
  7.2483708e-08 9.4971091e-07 2.2277349e-04 2.9146904e-05 2.6812913e-08]
 [9.9999309e-01 7.0278332e-13 3.5659536e-06 2.5072524e-09 3.3495309e-09
  2.2077063e-07 1.8981237e-06 2.6933108e-07 3.8185757e-10 9.1252411e-07]
 [9.4150749e-07 1.4605134e-12 1.1094733e-05 2.9119263e-09 9.9925488e-01
  5.7946875e-07 2.8529809e-07 3.6004163e-05 4.6944507e-08 6.9627690e-04]], shape=(5, 10), dtype=float32)
